max_width = 80
comment_width = 80
tab_spaces = 2
merge_derives = true
imports_granularity = "Module"
wrap_comments = true
where_single_line = false
use_try_shorthand = true
use_small_heuristics = "Off"
use_field_init_shorthand = true
type_punctuation_density = "Wide"
trailing_semicolon = false
trailing_comma = "Vertical"
struct_lit_single_line = false
struct_field_align_threshold = 0
spaces_around_ranges = true
space_before_colon = false
space_after_colon = true
reorder_modules = true
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_impl_items = true
remove_nested_parens = true
overflow_delimited_expr = true
normalize_doc_attributes = true
normalize_comments = true
newline_style = "Unix"
match_block_trailing_comma = true
match_arm_leading_pipes = "Always"
match_arm_blocks = false
inline_attribute_width = 0
indent_style = "Block"
imports_layout = "Vertical"
imports_indent = "Block"
hex_literal_case = "Upper"
hard_tabs = false
format_strings = true
format_macro_bodies = true
format_macro_matchers = true
format_generated_files = false
doc_comment_code_block_width = 80
format_code_in_doc_comments = true
force_multiline_blocks = false
force_explicit_abi = true
fn_single_line = false
fn_params_layout = "Vertical"
error_on_unformatted = false
error_on_line_overflow = false
enum_discrim_align_threshold = 0
empty_item_single_line = false
control_brace_style = "ClosingNextLine"
condense_wildcard_suffixes = true
combine_control_expr = true
color = "Auto"
chain_width = 40
brace_style = "AlwaysNextLine"
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
binop_separator = "Front"
attr_fn_like_width = 0
